### ISSUE TITLE
Relevancy of BlackCheck since userscripts.org is down?

### ISSUE THREAD

**Issue by maxxyme** [Tampermonkey/blackcheck#2]
Hello,

Just noticed why crawling the Tampermonkey change logs that you introduced BlackCheck in version 3.7.13
For now you only seem to have included 6 scripts from userscripts.org
But now it's been offline for a few days, is this still relevant?
http://www.ghacks.net/2014/05/09/userscripts-org-good-alternatives/

However, before the site went down, I installed a script called "Userscripts.org Scam Filter" that was intensively maintain to offer a protection against all scam/spam scripts at userscripts.org
If you want a copy, feel free to ask.

Maxx

**Comment by awunes** [comment]
There hasn't been an update for 2 years is this a needed thing?

**Comment by derjanb** [comment]
> There hasn't been an update for 2 years is this a needed thing?

Yes
